/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HelpIndex } from '../../models/help-index';

export interface HelpIndex$Params {
}

export function helpIndex(http: HttpClient, rootUrl: string, params?: HelpIndex$Params, context?: HttpContext): Observable<StrictHttpResponse<HelpIndex>> {
  const rb = new RequestBuilder(rootUrl, helpIndex.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HelpIndex>;
    })
  );
}

helpIndex.PATH = '/api/v1/help';
