/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The fixed numbers behind every estimate - shown on the page, set in [modules.catalog].
 */
export interface Assumptions {
  clampToTrained: boolean;
  fallbackContextLength: number;
  graphReserveBytes: number;
  tightRatio: number;
}
