/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * What the card offers Ollama: total - other programs - Ollama's reserve.
 */
export interface BudgetInfo {
  availableBytes?: (number | null);
  otherBytes: number;
  otherMeasuredAt?: (string | null);
  otherSource: 'measured' | 'assumed';
  reserveBytes: number;
  totalBytes?: (number | null);
}
