/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContextInfo } from '../models/context-info';
import { ContextStep } from '../models/context-step';
import { OpencodeFit } from '../models/opencode-fit';
import { Verdict } from '../models/verdict';
import { VramEstimate } from '../models/vram-estimate';

/**
 * A model from Ollama's library, checked BEFORE the pull: the same estimate and verdict as an installed
 * one, from the manifest and the GGUF header. Facts are from the time of the check, the verdict is fresh.
 */
export interface Candidate {
  architecture?: (string | null);
  capabilities?: Array<string>;
  capabilityNotes?: Array<string>;
  checkedAt: string;
  context?: (ContextInfo | null);
  downloadBytes: number;
  error?: (string | null);
  estimate?: (VramEstimate | null);
  family?: (string | null);
  fitsUpTo?: (number | null);
  headerBytes?: number;
  headerComplete?: boolean;
  host: string;
  installed?: boolean;
  loadsUpTo?: (number | null);
  name: string;
  notes?: Array<string>;
  opencode?: (OpencodeFit | null);
  page?: (string | null);
  parameterSize?: (string | null);
  parameters?: {
[key: string]: Array<string>;
};
  projectorBytes?: number;
  pull: string;
  quantization?: (string | null);
  requires?: (string | null);
  requiresOk?: (boolean | null);
  sameWeights?: Array<string>;
  simulated?: boolean;
  steps?: Array<ContextStep>;
  verdict?: (Verdict | null);
  weightsBytes: number;
}
