/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CandidateRequest {

  /**
   * as for ollama pull: qwen3-coder:30b, user/model:tag, hf.co/org/repo:tag
   */
  name: string;
}
