/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Assumptions } from '../models/assumptions';
import { BenchAccess } from '../models/bench-access';
import { BenchStatus } from '../models/bench-status';
import { BudgetInfo } from '../models/budget-info';
import { Candidate } from '../models/candidate';
import { CatalogModel } from '../models/catalog-model';
import { HardwareInfo } from '../models/hardware-info';
import { LibraryInfo } from '../models/library-info';
import { ModelGroup } from '../models/model-group';
import { OllamaState } from '../models/ollama-state';
import { RemovedModel } from '../models/removed-model';
import { ServerConfig } from '../models/server-config';
export interface CatalogOverview {
  asOf: string;
  assumptions: Assumptions;
  bench?: (BenchStatus | null);
  budget: BudgetInfo;
  candidates?: Array<Candidate>;
  groups: Array<ModelGroup>;
  hardware: HardwareInfo;
  library?: LibraryInfo;
  models: Array<CatalogModel>;
  ollama: OllamaState;
  refreshedAt?: (string | null);
  removed: Array<RemovedModel>;
  revision: number;
  server: ServerConfig;
  tests: BenchAccess;
}
