/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BenchStatus } from '../models/bench-status';
import { ContextInfo } from '../models/context-info';
import { Observation } from '../models/observation';
import { ParentInfo } from '../models/parent-info';
import { Verdict } from '../models/verdict';
import { VramEstimate } from '../models/vram-estimate';
export interface CatalogModel {
  architecture?: (string | null);
  benches?: Array<BenchStatus>;
  capabilities?: Array<string>;
  changes?: Array<string>;
  context: ContextInfo;
  depth: number;
  digest: string;
  estimate?: (VramEstimate | null);
  family?: (string | null);
  firstSeen?: (string | null);
  format?: (string | null);
  loaded?: boolean;
  modifiedAt?: (string | null);
  name: string;
  observations?: Array<Observation>;
  origin: string;
  parameterSize?: (string | null);
  parameters?: {
[key: string]: Array<string>;
};
  parent: ParentInfo;
  quantization?: (string | null);
  showError?: (string | null);
  sizeBytes: number;
  systemChars?: number;
  testable?: boolean;
  verdict: Verdict;
  weightsDigest?: (string | null);
}
