/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One context length of a candidate: what the card would have to hold, and the verdict.
 */
export interface ContextStep {
  extraBytes?: number;
  needBytes?: (number | null);
  state: 'fits' | 'tight' | 'split' | 'cpu' | 'unknown';
  tokens: number;
}
