/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContextInfo {
  clamped?: boolean;
  effective: number;
  own?: (number | null);
  parallel?: number;
  server?: (number | null);
  source: 'model' | 'server' | 'fallback';
  trained?: (number | null);
}
