/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardWarning {
  code: 'ollama_offline' | 'model_split' | 'model_cpu' | 'vram_low' | 'gpu_hot' | 'gpu_throttled' | 'ram_high' | 'disk_low' | 'service_down';
  level: 'critical' | 'warning' | 'info';
  message: string;
  subject: (string | null);
}
