/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardEvent {
  id: (number | null);
  kind: 'model_loaded' | 'model_unloaded' | 'model_reloaded' | 'offload_started' | 'offload_ended' | 'ollama_down' | 'ollama_up' | 'ollama_restarted' | 'ollama_updated' | 'ollama_crash';
  level: 'critical' | 'warning' | 'info';
  message: string;
  subject: (string | null);
  ts: string;
}
