/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardWarning } from '../models/dashboard-warning';
import { DiskUsage } from '../models/disk-usage';
import { GpuState } from '../models/gpu-state';
import { HostState } from '../models/host-state';
import { LoadedModel } from '../models/loaded-model';
import { ServiceStatus } from '../models/service-status';
import { SourceError } from '../models/source-error';
export interface DashboardSnapshot {
  disks: (Array<DiskUsage> | null);
  errors: Array<SourceError>;
  gpu: (GpuState | null);
  host: (HostState | null);
  models: Array<LoadedModel>;
  nodeId: string;
  ollamaOnline: boolean;
  ollamaVersion: (string | null);
  services: Array<ServiceStatus>;
  simulated: Array<string>;
  ts: string;
  warnings: Array<DashboardWarning>;
}
