/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExportDocument {
  content: string;
  detail: 'short' | 'full';
  filename: string;
  format: 'md' | 'json';
  mediaType: string;
  tokens: number;
}
