/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GpuState {
  driverVersion: (string | null);
  fanPercent: (number | null);
  name: string;
  powerLimitW: (number | null);
  powerW: (number | null);
  tempC: (number | null);
  throttleReasons: Array<string>;
  utilPercent: (number | null);
  vramTotalMib: number;
  vramUsedMib: number;
}
