/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HardwareInfo {
  gpuName?: (string | null);
  key?: (string | null);
  note?: (string | null);
  vramTotalBytes?: (number | null);
}
