/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModuleInfo } from '../models/module-info';
export interface HealthInfo {
  database: boolean;
  modules: Array<ModuleInfo>;
  status: 'ok' | 'degraded';
  version: string;
}
