/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HelpDoc {
  key: string;
  markdown: string;
  moduleState: ('loaded' | 'starting' | 'running' | 'failed' | 'disabled' | null);
  title: string;
}
