/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProcessInfo } from '../models/process-info';
export interface HostState {
  cpuCount: number;
  cpuPercent: (number | null);
  processes: Array<ProcessInfo>;
  ramTotalBytes: number;
  ramUsedBytes: number;
  uptimeS: number;
}
