/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JobProgress } from '../models/job-progress';
import { SourceReport } from '../models/source-report';
export interface JobStatus {
  asOf: string;
  cancelRequested?: boolean;
  createdAt: string;
  current?: (JobProgress | null);
  error?: (string | null);
  finishedAt?: (string | null);
  id: string;
  maxChars: number;
  model: string;
  revision: number;
  sources: Array<SourceReport>;
  startedAt?: (string | null);
  state: 'queued' | 'running' | 'done' | 'failed' | 'cancelled';
}
