/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JobProgress {
  collection: string;
  done?: number;
  file?: (string | null);
  phase: 'scan' | 'embed' | 'cleanup';
  total?: number;
}
