/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoadedModel {
  contextLength: (number | null);
  digest: string;
  expiresAt: (string | null);
  family: (string | null);
  gpuRatio: (number | null);
  name: string;
  parameterSize: (string | null);
  pinned: boolean;
  placement: 'gpu' | 'split' | 'cpu' | 'unknown';
  quantization: (string | null);
  sizeBytes: number;
  unloading: boolean;
  vramBytes: number;
}
