/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LogEntry } from '../models/log-entry';
export interface LogPage {
  entries: Array<LogEntry>;
  nextCursor: (string | null);
}
