/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LogFileInfo } from '../models/log-file-info';
export interface LogSourceInfo {
  available: boolean;
  files: Array<LogFileInfo>;
  format: string;
  key: string;
  title: string;
}
