/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LogEntry {
  exc?: (string | null);
  file: string;
  level: (string | null);
  logger: (string | null);
  msg: string;
  source: string;
  ts: (string | null);
}
