/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { McpTool } from '../models/mcp-tool';
export interface McpToolList {
  error?: (string | null);
  fetchedAt: string;
  protocolVersion?: (string | null);
  serverName?: (string | null);
  serverVersion?: (string | null);
  tools: Array<McpTool>;
}
