/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { McpToolParam } from '../models/mcp-tool-param';
export interface McpTool {
  description?: (string | null);
  name: string;
  params: Array<McpToolParam>;
  title?: (string | null);
}
