/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface McpToolParam {
  default?: (string | null);
  description?: (string | null);
  name: string;
  required: boolean;
  type: string;
}
