/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModuleInfo {
  error?: (string | null);
  icon: string;
  key: string;
  order: number;
  state: 'loaded' | 'starting' | 'running' | 'failed' | 'disabled';
  title: string;
}
