/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Observation {
  current: boolean;
  firstSeen: string;
  gpuRatio: (number | null);
  hardware: (string | null);
  lastSeen: string;
  loads: number;
  numCtx: (number | null);
  placement: 'gpu' | 'split' | 'cpu' | 'unknown';
  sizeBytes: number;
  vramBytes: number;
}
