/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OllamaState {
  error?: (string | null);
  online: boolean;
  simulated?: boolean;
  version?: (string | null);
}
