/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Verdict } from '../models/verdict';

/**
 * Can OpenCode work with this model on this card? Tools measured, context and VRAM computed.
 */
export interface OpencodeFit {
  atMin?: (Verdict | null);
  block: string;
  configKey: string;
  context: number;
  evalTps?: (number | null);
  minContext: number;
  reasons: Array<string>;
  state: 'fits' | 'maybe' | 'no' | 'unknown';
  toolsAt?: (string | null);
  toolsPassed?: (number | null);
  toolsSimulated?: boolean;
  toolsTotal?: (number | null);
}
