/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * What the runner held beyond Ollama's count in the newest test run of the same weights on this GPU.
 */
export interface OverheadInfo {
  extraBytes: number;
  measuredAt: string;
  measuredBytes: number;
  model: string;
  reserveBytes: number;
}
