/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ParentInfo {
  declared?: (string | null);
  installed?: boolean;
  resolved?: (string | null);
  via?: ('declared' | 'weights' | null);
}
