/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PortInfo {
  checkedAt?: (string | null);
  managed?: boolean;
  open: (boolean | null);
  pid?: (number | null);
  port: number;
  process?: (string | null);
}
