/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContextInfo } from '../models/context-info';
import { Verdict } from '../models/verdict';
import { VramEstimate } from '../models/vram-estimate';

/**
 * Before a test run: what loading this model with this context would cost, and whether it may run.
 */
export interface Preflight {
  allowed: boolean;
  context: ContextInfo;
  estimate?: (VramEstimate | null);
  name: string;
  needsConfirm: boolean;
  reason?: (string | null);
  suggestions?: Array<number>;
  verdict: Verdict;
  willUnload?: Array<string>;
}
