/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProcessInfo {
  cmdline: (string | null);
  cpuPercent: (number | null);
  name: string;
  pid: number;
  rssBytes: (number | null);
}
