/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SearchHit {
  filename?: (string | null);
  id: string;
  score: number;
  text?: (string | null);
  truncated?: (boolean | null);
}
