/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceStatus {
  error: (string | null);
  httpStatus: (number | null);
  key: string;
  latencyMs: (number | null);
  title: string;
  up: boolean;
}
