/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileNote } from '../models/file-note';
import { SecretNote } from '../models/secret-note';
export interface SourceReport {
  collection: string;
  created?: boolean;
  done?: number;
  durationS?: (number | null);
  embedS?: (number | null);
  empty?: number;
  error?: (string | null);
  files?: number;
  finishedAt?: (string | null);
  indexed?: number;
  listsCut?: boolean;
  missingDirs?: Array<string>;
  removed?: number;
  root?: (string | null);
  secret?: number;
  secretHits?: Array<SecretNote>;
  skipped?: number;
  skippedFiles?: Array<FileNote>;
  startedAt?: (string | null);
  state?: 'pending' | 'running' | 'done' | 'failed' | 'cancelled';
  title: string;
  truncated?: number;
  truncatedFiles?: Array<FileNote>;
}
