/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StoreInfo {
  error?: (string | null);
  local: boolean;
  mode: 'qdrant' | 'memory';
  port?: (number | null);
  reachable: boolean;
  url: (string | null);
  version?: (string | null);
}
