/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ToolCase } from '../models/tool-case';

/**
 * Did the model answer with structured tool calls? Three agent-like requests via /api/chat.
 */
export interface ToolCheck {
  cases?: Array<ToolCase>;
  passed: number;
  simulated?: boolean;
  skipped?: (string | null);
  total: number;
}
