/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ToolCase {
  detail: string;
  key: string;
  label: string;
  ok: boolean;
  seconds?: (number | null);
  thinking?: boolean;
}
