/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DerivedTag } from '../models/derived-tag';

/**
 * What the team uses a model for - set on the page, kept by name (survives re-pulls).
 */
export interface UsageInfo {
  derived?: Array<DerivedTag>;
  note?: (string | null);
  tags?: Array<'opencode' | 'openwebui' | 'rag' | 'test' | 'remove'>;
  updatedAt?: (string | null);
}
