/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsageRequest {
  name: string;
  note?: (string | null);
  tags?: Array<'opencode' | 'openwebui' | 'rag' | 'test' | 'remove'>;
}
