/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Verdict {
  availableBytes?: (number | null);
  basis: 'measured' | 'estimated' | 'none';
  message: string;
  needBytes?: (number | null);
  state: 'fits' | 'tight' | 'split' | 'cpu' | 'unknown';
}
