/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VramEstimate {
  confidence?: 'normal' | 'low';
  driverBytes: number;
  graphBytes: number;
  kvBytes?: (number | null);
  kvType: string;
  notes?: Array<string>;
  tokens: number;
  totalBytes?: (number | null);
  weightsBytes: number;
}
