/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VramEstimate {
  calibrated?: (string | null);
  confidence?: 'normal' | 'low';
  formulaBytes?: (number | null);
  graphBytes: number;
  kvBytes?: (number | null);
  kvType: string;
  needBytes?: (number | null);
  notes?: Array<string>;
  tokens: number;
  weightsBytes: number;
}
