/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CoreHealth$Params as CoreHealth$Params } from './fn/core/core-health';
export { coreHealth as coreHealth } from './fn/core/core-health';
export type { CoreModules$Params as CoreModules$Params } from './fn/core/core-modules';
export { coreModules as coreModules } from './fn/core/core-modules';
