/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LogPage } from '../../models/log-page';

export interface LogsEntries$Params {

/**
 * source key from /sources, e.g. control-center
 */
  source: string;

/**
 * minimum level; hides lines without a level
 */
  level?: ('DEBUG' | 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL' | null);

/**
 * logger prefix, e.g. control_center.modules.logs
 */
  logger?: (string | null);

/**
 * logger prefixes to hide, e.g. uvicorn.access
 */
  exclude?: Array<string>;

/**
 * case-insensitive text search
 */
  q?: (string | null);
  since?: (string | null);
  until?: (string | null);
  limit?: number;

/**
 * nextCursor of the previous page
 */
  cursor?: (string | null);
}

export function logsEntries(http: HttpClient, rootUrl: string, params: LogsEntries$Params, context?: HttpContext): Observable<StrictHttpResponse<LogPage>> {
  const rb = new RequestBuilder(rootUrl, logsEntries.PATH, 'get');
  if (params) {
    rb.query('source', params.source, {});
    rb.query('level', params.level, {});
    rb.query('logger', params.logger, {});
    rb.query('exclude', params.exclude, {});
    rb.query('q', params.q, {});
    rb.query('since', params.since, {});
    rb.query('until', params.until, {});
    rb.query('limit', params.limit, {});
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LogPage>;
    })
  );
}

logsEntries.PATH = '/api/v1/logs/entries';
