/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LogSourceInfo } from '../../models/log-source-info';

export interface LogsSources$Params {
}

export function logsSources(http: HttpClient, rootUrl: string, params?: LogsSources$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LogSourceInfo>>> {
  const rb = new RequestBuilder(rootUrl, logsSources.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LogSourceInfo>>;
    })
  );
}

logsSources.PATH = '/api/v1/logs/sources';
