/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RagOverview } from '../../models/rag-overview';

export interface RagOverview$Params {
}

export function ragOverview(http: HttpClient, rootUrl: string, params?: RagOverview$Params, context?: HttpContext): Observable<StrictHttpResponse<RagOverview>> {
  const rb = new RequestBuilder(rootUrl, ragOverview.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RagOverview>;
    })
  );
}

ragOverview.PATH = '/api/v1/rag/overview';
