/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobStatus } from '../../models/job-status';

export interface RagCancelJob$Params {
  job_id: string;
}

export function ragCancelJob(http: HttpClient, rootUrl: string, params: RagCancelJob$Params, context?: HttpContext): Observable<StrictHttpResponse<JobStatus>> {
  const rb = new RequestBuilder(rootUrl, ragCancelJob.PATH, 'post');
  if (params) {
    rb.path('job_id', params.job_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobStatus>;
    })
  );
}

ragCancelJob.PATH = '/api/v1/rag/jobs/{job_id}/cancel';
