/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobRequest } from '../../models/job-request';
import { JobStatus } from '../../models/job-status';

export interface RagStartJob$Params {
      body: JobRequest
}

export function ragStartJob(http: HttpClient, rootUrl: string, params: RagStartJob$Params, context?: HttpContext): Observable<StrictHttpResponse<JobStatus>> {
  const rb = new RequestBuilder(rootUrl, ragStartJob.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JobStatus>;
    })
  );
}

ragStartJob.PATH = '/api/v1/rag/jobs';
