/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RagDeleteCollection$Params {
  name: string;

/**
 * must repeat the collection name
 */
  confirm: string;
}

export function ragDeleteCollection(http: HttpClient, rootUrl: string, params: RagDeleteCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, ragDeleteCollection.PATH, 'delete');
  if (params) {
    rb.path('name', params.name, {});
    rb.query('confirm', params.confirm, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

ragDeleteCollection.PATH = '/api/v1/rag/collections/{name}';
