/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JobStatus } from '../../models/job-status';

export interface RagJobs$Params {
}

export function ragJobs(http: HttpClient, rootUrl: string, params?: RagJobs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<JobStatus>>> {
  const rb = new RequestBuilder(rootUrl, ragJobs.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<JobStatus>>;
    })
  );
}

ragJobs.PATH = '/api/v1/rag/jobs';
