/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CandidateRequest } from '../../models/candidate-request';
import { CandidateResult } from '../../models/candidate-result';

export interface CatalogCheckCandidate$Params {
      body: CandidateRequest
}

export function catalogCheckCandidate(http: HttpClient, rootUrl: string, params: CatalogCheckCandidate$Params, context?: HttpContext): Observable<StrictHttpResponse<CandidateResult>> {
  const rb = new RequestBuilder(rootUrl, catalogCheckCandidate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CandidateResult>;
    })
  );
}

catalogCheckCandidate.PATH = '/api/v1/catalog/candidates';
