/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Preflight } from '../../models/preflight';

export interface CatalogPreflight$Params {

/**
 * installed model name
 */
  name: string;

/**
 * context to check; empty = the effective one
 */
  num_ctx?: (number | null);
}

export function catalogPreflight(http: HttpClient, rootUrl: string, params: CatalogPreflight$Params, context?: HttpContext): Observable<StrictHttpResponse<Preflight>> {
  const rb = new RequestBuilder(rootUrl, catalogPreflight.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('num_ctx', params.num_ctx, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Preflight>;
    })
  );
}

catalogPreflight.PATH = '/api/v1/catalog/preflight';
