/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardHistory } from '../../models/dashboard-history';

export interface DashboardHistory$Params {

/**
 * time span back from now
 */
  range?: '1h' | '6h' | '24h' | '7d' | '30d';

/**
 * empty = all metrics
 */
  metrics?: Array<'gpu_util' | 'vram_used_mib' | 'temp_c' | 'power_w' | 'cpu_percent' | 'ram_percent'>;
}

export function dashboardHistory(http: HttpClient, rootUrl: string, params?: DashboardHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardHistory>> {
  const rb = new RequestBuilder(rootUrl, dashboardHistory.PATH, 'get');
  if (params) {
    rb.query('range', params.range, {});
    rb.query('metrics', params.metrics, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardHistory>;
    })
  );
}

dashboardHistory.PATH = '/api/v1/dashboard/history';
