/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardSnapshot } from '../../models/dashboard-snapshot';

export interface DashboardSnapshot$Params {
}

export function dashboardSnapshot(http: HttpClient, rootUrl: string, params?: DashboardSnapshot$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardSnapshot>> {
  const rb = new RequestBuilder(rootUrl, dashboardSnapshot.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardSnapshot>;
    })
  );
}

dashboardSnapshot.PATH = '/api/v1/dashboard/snapshot';
