/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventPage } from '../../models/event-page';

export interface DashboardEvents$Params {
  limit?: number;

/**
 * nextBefore of the previous page
 */
  before?: (number | null);
}

export function dashboardEvents(http: HttpClient, rootUrl: string, params?: DashboardEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<EventPage>> {
  const rb = new RequestBuilder(rootUrl, dashboardEvents.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('before', params.before, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EventPage>;
    })
  );
}

dashboardEvents.PATH = '/api/v1/dashboard/events';
