/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExportDocument } from '../../models/export-document';

export interface DashboardExport$Params {

/**
 * md = Markdown with YAML header, json
 */
  format?: 'md' | 'json';

/**
 * short = overview, full = everything
 */
  detail?: 'short' | 'full';

/**
 * empty = snapshot, events, history
 */
  parts?: Array<'snapshot' | 'events' | 'history'>;

/**
 * history time span
 */
  range?: '1h' | '6h' | '24h' | '7d' | '30d';

/**
 * replace host names, IPs and user folders, drop command lines
 */
  anonymize?: boolean;
}

export function dashboardExport(http: HttpClient, rootUrl: string, params?: DashboardExport$Params, context?: HttpContext): Observable<StrictHttpResponse<ExportDocument>> {
  const rb = new RequestBuilder(rootUrl, dashboardExport.PATH, 'get');
  if (params) {
    rb.query('format', params.format, {});
    rb.query('detail', params.detail, {});
    rb.query('parts', params.parts, {});
    rb.query('range', params.range, {});
    rb.query('anonymize', params.anonymize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExportDocument>;
    })
  );
}

dashboardExport.PATH = '/api/v1/dashboard/export';
