/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthInfo } from '../../models/health-info';

export interface CoreHealth$Params {
}

export function coreHealth(http: HttpClient, rootUrl: string, params?: CoreHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthInfo>> {
  const rb = new RequestBuilder(rootUrl, coreHealth.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HealthInfo>;
    })
  );
}

coreHealth.PATH = '/api/v1/health';
